### ISSUE TITLE
Buildroot Environment Bringup for BeagleBone Black

### ISSUE THREAD

**Issue by parthkharade** [parthkharade/ECEN-5713-FinalProject#1]
Original Issue : Create a Buildroot image for Beaglebone Black
Updated Issue : Create a Buildroot image for Raspberry Pi 3B with Ethernet support for SSH.
Updated Blockers related to BeagleBone Black : UART setup and Ethernet for SSH

Original DoD : Can successfully build image and boot up BeagleBone Black using that image.
Updated Dod : Can successfully build image and boot up Raspberry Pi 3B Black using that image with Ethernet support working for SSH.
Blockers related to Raspberry Pi 3B:  None

**Comment by pranjalgupta1901** [comment]
# Buildroot Environment Bringup of BeagleBone Black
## Blockers 
- UART Setup
- Ethernet Setup in order to do SSH
## Work Done to solve the blockers
- I started with building image for BeagleBone Black using Buildroot, setting its UART for serial terminal and SSH using ethernet. The Image was successfully built and the board was booted everytime using SD Card.
- I was able to see that ethernet was getting detected and its driver is also working fine. I was not able to do ssh even though I was connected with the internet and I was able to send messages but was able to recieve it as the messages were getting lost somewhere. I found out that there is a hardware problem associated with the Ethernet I had in my board which is LAN 8710. Therefore, to proceed with the project, I went ahead with building the image for Raspberry Pi 3B.

# Buildroot Environment Bringup of Raspberry Pi 3B
- Raspberry Pi successfully booting up with SD Card with SSH support with the help of Buildrooot Image
- Blockers : No Blockers during the process

**Comment by pranjalgupta1901** [comment]
# Buildroot Environment Bringup of BeagleBone Black

## Blockers
-  UART Setup
-  Ethernet Setup in order to do SSH

## Work done
 -  I started with building image for BeagleBone Black using Buildroot, setting its UART for serial terminal and SSH using ethernet. The Image was successfully built and the board was booted everytime using SD Card.
- I was able to see that ethernet was getting detected and its driver is also working fine. I was not able to do ssh even though I was connected with the internet and I was able to send messages but was able to recieve it as the messages were getting lost somewhere. I found out that there is a hardware problem associated with the Ethernet I had in my board which is LAN 8710. This issue is also addressed by BeagleBone officially whose reference can be found this [link](https://github.com/beagleboard/beaglebone-black/issues/4). Therefore, to proceed with the project and due to non availability of a different board, I went ahead with building the image for Raspberry Pi 3B.

# Buildroot Environment Bringup of Raspberry Pi 3B
## Blockers
- None
## Work Done
- Raspberry Pi successfully booting up with SD Card with SSH support using Ethernet with the help of Buildroot Image


![Image](https://github.com/parthkharade/ECEN-5713-FinalProject/assets/83120222/19972fd7-ff28-4fdd-a884-48e8bdd80f0f)


# Update Regarding BeagleBone Ethernet Issue
- I was able to do ssh support with Ethernet. The things i did in order to make it work:
-- Rebuilt the image with dhcpcd uitlity( it was there before)
-- Removed OpenSSH as prevously both dropbear and OpenSSH was installed
--  added interface details for static IP in /etc/network/interfaces(was there before but was not working)
-- Changed the buildroot version to the latest 2024.02



![Image](https://github.com/parthkharade/ECEN-5713-FinalProject/assets/83120222/b3bcaea5-5a93-4d19-8607-883b8a5e83f0)

- The main thing was the driver, now the ethernet got connected with the router perfectlty as seen in the image below.

![Image](https://github.com/parthkharade/ECEN-5713-FinalProject/assets/83120222/c115107a-638d-4618-9991-bd2dd5a1257b)



![Image](https://github.com/parthkharade/ECEN-5713-FinalProject/assets/83120222/81766d8a-dc51-4ed8-8d3e-b1ab912b148d)



![Image](https://github.com/parthkharade/ECEN-5713-FinalProject/assets/83120222/bff6e83e-5028-4eaa-861d-73420aed5eaf)


- There can be a hardware issue as I had most of things available in my previous build but I will check it later by resetting the board multiple times.
